export enum ShipmentStatus {
  PROCESSING = 'PROCESSING',
  READY_TO_SHIP = 'READY TO SHIP',
  IN_TRANSIT = 'IN TRANSIT',
  DELIVERED = 'DELIVERED',
  DELIVERY_FAILED = 'DELIVERY_FAILED',
  CANCELLED = 'CANCELLED',
  DELAYED = 'DELAYED',
}
